### ISSUE TITLE
Issue with Python 3.10

### ISSUE THREAD

**Issue by scottwestover** [ItsKarma/aws-cli#7]
Not sure if this is the right place to report this issue, but I just started getting the following error today in my existing workflows.

It looks like the docker image is currently pointed to `3-alpine`, and this was recently updated to use Python 3.10. The aws-cli page mentions that it now supports Python 3.10. 

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python3.10/site-packages/awscli/clidriver.py", line 68, in main
    driver = create_clidriver()
  File "/usr/local/lib/python3.10/site-packages/awscli/clidriver.py", line 77, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/usr/local/lib/python3.10/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python3.10/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python3.10/site-packages/awscli/handlers.py", line 42, in <module>
    from awscli.customizations.history import register_history_mode
  File "/usr/local/lib/python3.10/site-packages/awscli/customizations/history/__init__.py", line 24, in <module>
    from awscli.customizations.history.db import DatabaseConnection
  File "/usr/local/lib/python3.10/site-packages/awscli/customizations/history/db.py", line 19, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

**Comment by edmarbarros** [comment]
Currently experiencing the same issue here.

@scottwestover @daniterrin did you had any success solving that?

**Comment by jpeace-pro** [comment]
Currently experiencing same issue. Looked at trying this out and suggesting that to this branch:
https://stackoverflow.com/questions/59636631/aws-cli-with-python-3-9-0a1-error-from-collections-import-mutablemapping

**Comment by daniterrin** [comment]
@edmarbarros I went for a pretty similar approach. I'm now using the official docker image of aws-cli in my CI-CD pipeline in Github. You can find more info here aws/aws-cli#3553.

I assume that the issue might also be fixed by changing the version of aws-cli that dockerfile retrieves from 3-alpine. However, I can't test it.

**Comment by ItsKarma** [comment]
Thank you for this and apologies for the incredibly delayed response.  
I believe this should be resolved now with https://github.com/ItsKarma/aws-cli/pull/8.
Please let me know if anyone is still experiencing this issue and we can re-open.
